import { Router, type Request, type Response } from 'express';
import path from 'path';
import fs from 'fs-extra';
import { PDFDocument, PDFPage, degrees, PDFOperator } from 'pdf-lib';
import potpack from 'potpack'; 
import { UPLOAD_DIR } from './upload.js';
import { DATA_DIR } from '../db.js';
import { execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

const router = Router();

interface DTFFileRequest {
    url: string;
    quantity: number;
}

interface DTFGenerateRequest {
    rollWidthMm: number;
    rollLengthMm: number; // 0 for auto/infinite
    paddingMm: number;
    files: DTFFileRequest[];
}

interface Item {
    w: number;
    h: number;
    sourceIndex: number;
    x?: number;
    y?: number;
    pageIndex?: number;
    rotated?: boolean; // New: Track if item was rotated
}

// Simple Guillotine Bin Packing
// We maintain a list of free rectangles.
interface Rect {
    x: number;
    y: number;
    w: number;
    h: number;
}

class GuillotinePacker {
    width: number;
    height: number;
    freeRects: Rect[];

    constructor(width: number, height: number) {
        this.width = width;
        this.height = height;
        this.freeRects = [{ x: 0, y: 0, w: width, h: height }];
    }

    fit(w: number, h: number): { x: number, y: number, rotated: boolean } | null {
        // We want to maximize packing efficiency.
        // We are packing into a fixed height strip.
        // We want to minimize Width usage.
        // This is equivalent to packing into a bin with Fixed Height and Minimized Width.
        
        // Let's use "Best Short Side Fit" (BSSF) strategy.
        // This minimizes the smaller leftover dimension.
        // It's known to be better than First Fit for packing density.
        
        let bestScore = Number.MAX_VALUE;
        let bestRectIndex = -1;
        let bestRotated = false;
        
        // Iterate all free rects to find best fit
        for (let i = 0; i < this.freeRects.length; i++) {
            const rect = this.freeRects[i];
            
            // Check Normal (W x H)
            if (w <= rect.w && h <= rect.h) {
                const leftoverHoriz = Math.abs(rect.w - w);
                const leftoverVert = Math.abs(rect.h - h);
                const shortSideFit = Math.min(leftoverHoriz, leftoverVert);
                
                // Tie-breaker: Maximize Long Side Fit? Or prioritize Leftmost (X)?
                // To minimize total width, we should penalize large X.
                // But pure BSSF ignores position.
                // Let's combine BSSF with a penalty for X position to encourage filling left.
                // But penalty shouldn't override a perfect fit.
                
                // Let's stick to BSSF first.
                // Actually, if we just use BSSF, we might pick a hole far right.
                // But our freeRects are generated by splitting.
                
                // Let's use a "Bottom-Left" heuristic combined with BSSF?
                // Or simply: "Best Area Fit" (Minimize wasted area in the rect)?
                // Wasted Area = (rect.w * rect.h) - (w * h).
                // This means we pick the smallest rect that fits the item.
                // This is "Best Fit".
                
                // Let's try Best Short Side Fit as primary score.
                const score = shortSideFit;
                
                if (score < bestScore) {
                    bestScore = score;
                    bestRectIndex = i;
                    bestRotated = false;
                }
            }
            
            // Check Rotated (H x W)
            if (h <= rect.w && w <= rect.h) {
                const leftoverHoriz = Math.abs(rect.w - h);
                const leftoverVert = Math.abs(rect.h - w);
                const shortSideFit = Math.min(leftoverHoriz, leftoverVert);
                
                const score = shortSideFit;
                
                if (score < bestScore) {
                    bestScore = score;
                    bestRectIndex = i;
                    bestRotated = true;
                }
            }
        }
        
        // If we found a fit
        if (bestRectIndex !== -1) {
            // Tie-breaking or X-minimization logic:
            // If multiple rects have same bestScore, pick the one with smallest X?
            // The loop order matters. If we sort freeRects by X, we pick leftmost among best scores implicitly?
            // No, we scan all.
            // We need to check if score == bestScore, then prefer lower X.
            
            // Let's refine the loop above.
        }
        
        // Re-run with X preference
        bestScore = Number.MAX_VALUE;
        bestRectIndex = -1;
        bestRotated = false;
        
        // Sort free rects by X (Leftmost) then Y (Topmost)
        // This helps tie-breaking for "Leftmost" choice
        this.freeRects.sort((a, b) => {
             if (Math.abs(a.x - b.x) > 1) return a.x - b.x;
             return a.y - b.y;
        });
        
        for (let i = 0; i < this.freeRects.length; i++) {
            const rect = this.freeRects[i];
            
            // Normal
            if (w <= rect.w && h <= rect.h) {
                const leftoverHoriz = Math.abs(rect.w - w);
                const leftoverVert = Math.abs(rect.h - h);
                const shortSideFit = Math.min(leftoverHoriz, leftoverVert);
                const score = shortSideFit;
                
                if (score < bestScore) {
                    bestScore = score;
                    bestRectIndex = i;
                    bestRotated = false;
                }
            }
            
            // Rotated
            if (h <= rect.w && w <= rect.h) {
                const leftoverHoriz = Math.abs(rect.w - h);
                const leftoverVert = Math.abs(rect.h - w);
                const shortSideFit = Math.min(leftoverHoriz, leftoverVert);
                const score = shortSideFit;
                
                if (score < bestScore) {
                    bestScore = score;
                    bestRectIndex = i;
                    bestRotated = true;
                }
            }
        }
        
        if (bestRectIndex !== -1) {
            const rect = this.freeRects[bestRectIndex];
            const fitX = rect.x;
            const fitY = rect.y;
            
            const actualW = bestRotated ? h : w;
            const actualH = bestRotated ? w : h;
            
            this.splitFreeRect(rect, bestRectIndex, actualW, actualH);
            return { x: fitX, y: fitY, rotated: bestRotated };
        }
        
        return null;
    }

    splitFreeRect(freeRect: Rect, index: number, w: number, h: number) {
        // We want to fill Y (Height) first (Column packing).
        // So we want to preserve vertical space for next items in this column.
        
        // Vertical Split:
        // Rect Right: x+w, y, free.w-w, free.h (Tall strip to right)
        // Rect Bottom: x, y+h, w, free.h-h (Rest of column below)
        
        // If we use Vertical Split, we create a specific slot below (width w).
        // This forces next item below to be width <= w.
        // If next item is wider, it must go to Rect Right.
        
        // Horizontal Split:
        // Rect Right: x+w, y, free.w-w, h (Short strip to right)
        // Rect Bottom: x, y+h, free.w, free.h-h (Wide strip below)
        
        // If we use Horizontal Split, Rect Bottom is wide.
        // Next item can be wider than current item and still fit below.
        // This is better for "Shelf" packing where we fill a shelf of height h.
        
        // But here height is fixed (56cm). We are filling "Columns".
        // Actually, we are filling the "Sheet".
        
        // If we want to pack tight, we should use "Shorter Axis Split" (SAS) rule?
        // Or "Maximize Area" rule?
        
        // Given the user wants "durcheinander" and "optimal":
        // Let's use the standard Guillotine Split Rule:
        // Split along the axis that minimizes the shorter side of the leftover rectangles?
        // Or "Split Horizontally" if w < h?
        
        // Let's use a dynamic split:
        // If free.w < free.h, split horizontally?
        
        // Let's try minimizing the "waste" aspect.
        // Actually, for fixed height strip packing, keeping the "bottom" rect available as wide as possible is often good?
        // No, we want to fill the "left" side.
        
        // Let's stick to Vertical Split (creates Rect Bottom restricted to w).
        // This is standard for Column packing.
        // BUT: User complained about gaps.
        // Gaps appear if `w` is small, and we can't fit anything in `Rect Bottom`.
        // Then `Rect Bottom` is wasted.
        
        // Maybe we should allow items to be placed in `Rect Right` even if `Rect Bottom` is empty?
        // Yes, the packer does that.
        
        // What if we try `Horizontal Split`?
        // Rect Bottom is full width.
        // If we place Item 1 (top-left). Rect Bottom is (0, h, W, H-h).
        // Next item can be placed at (0, h).
        // This effectively fills Top-to-Bottom.
        // This creates "Shelves" defined by item height? No, just fills Y.
        
        // Let's try Horizontal Split.
        // It allows wider items to be placed below narrow items.
        // This might reduce gaps!
        
        const usedRect = freeRect;
        this.freeRects.splice(index, 1); 
        
        // Horizontal Split strategy
        // Rect 1 (Bottom): x, y + h, free.w, free.h - h
        // Rect 2 (Right): x + w, y, free.w - w, h
        
        // Add Bottom first (so it's picked first by Left-sort if x is same)
        if (usedRect.h > h) {
            this.freeRects.push({
                x: usedRect.x,
                y: usedRect.y + h,
                w: usedRect.w, // Full remaining width
                h: usedRect.h - h
            });
        }
        
        // Add Right
        if (usedRect.w > w) {
            this.freeRects.push({
                x: usedRect.x + w,
                y: usedRect.y,
                w: usedRect.w - w,
                h: h // Restricted height
            });
        }
    }
}

router.post('/generate', async (req: Request, res: Response) => {
    try {
        const { rollWidthMm, rollLengthMm, paddingMm, files } = req.body as DTFGenerateRequest;

        if (!files || files.length === 0) {
            res.status(400).json({ success: false, error: 'Keine Dateien ausgewählt.' });
            return;
        }

        // 1. Load all source PDFs and measure dimensions
        const sourceDocs: { 
            pdf: PDFDocument, 
            width: number, 
            height: number,
            originalUrl: string
        }[] = [];

        const paddingPoints = (paddingMm || 0) * 2.83465;
        
        // Final Interpretation based on "56cm hoch ... 8,5cm breit" where "56cm rollenbreite eingabe":
        // Input 1 (rollWidthMm) = PDF HEIGHT (Fixed).
        // Input 2 (rollLengthMm) = PDF WIDTH (Variable/Max).
        
        const pdfHeightFixedPoints = rollWidthMm * 2.83465; // Fixed Height
        const pdfMaxWidthPoints = rollLengthMm > 0 ? rollLengthMm * 2.83465 : Number.MAX_VALUE; // Max Width

        // Packer Config:
        // We pack into a strip of Fixed Height and Infinite/Max Width.
        // We want to minimize Width usage.
        
        const PACKER_HEIGHT = pdfHeightFixedPoints;
        const PACKER_WIDTH = pdfMaxWidthPoints === Number.MAX_VALUE ? 100000 : pdfMaxWidthPoints;

        const itemsToPack: Item[] = [];

        for (const file of files) {
            // ... (file loading same)
            const filename = path.basename(file.url);
            const filePath = path.join(UPLOAD_DIR, filename);

            if (!fs.existsSync(filePath)) {
                console.warn(`File not found: ${filePath}`);
                continue;
            }

            try {
                const fileBuffer = await fs.readFile(filePath);
                let width = 0;
                let height = 0;
                let pdfDoc: PDFDocument | null = null;

                if (filename.toLowerCase().endsWith('.pdf')) {
                    pdfDoc = await PDFDocument.load(fileBuffer);
                    const firstPage = pdfDoc.getPages()[0];
                    const { width: w, height: h } = firstPage.getSize();
                    width = w; 
                    height = h;
                } else if (filename.toLowerCase().endsWith('.png')) {
                    pdfDoc = await PDFDocument.create();
                    const image = await pdfDoc.embedPng(fileBuffer);
                    width = image.width;
                    height = image.height;
                    const page = pdfDoc.addPage([width, height]);
                    page.drawImage(image, { x: 0, y: 0, width, height });
                } else {
                    console.warn(`Unsupported file type: ${filename}`);
                    continue;
                }

                if (pdfDoc) {
                    const sourceIndex = sourceDocs.length;
                    sourceDocs.push({
                        pdf: pdfDoc,
                        width,
                        height,
                        originalUrl: file.url
                    });

                    for (let i = 0; i < file.quantity; i++) {
                        itemsToPack.push({
                            w: width + paddingPoints,
                            h: height + paddingPoints,
                            sourceIndex
                        });
                    }
                }
            } catch (err) {
                console.error(`Error processing file ${filename}:`, err);
            }
        }

        if (itemsToPack.length === 0) {
            res.status(400).json({ success: false, error: 'Keine gültigen Dateien verarbeitet.' });
            return;
        }

        // 2. Perform Bin Packing (Guillotine)
        // Config: 
        // Container Height = Fixed (User RollWidth)
        // Container Width = Variable (User RollLength)
        
        // We want to fill Y (Height) first (Columns), then X (Width).
        // Sorting items?
        // To fill Height efficiently, sorting by Height Descending is good.
        // Or Width Descending?
        // Let's use Height Descending to fit tall items first into the fixed height strip.
        itemsToPack.sort((a, b) => b.h - a.h);

        let pages: Item[][] = [];
        let currentPageItems: Item[] = [];
        
        let packer = new GuillotinePacker(PACKER_WIDTH, PACKER_HEIGHT);
        let currentPageIndex = 0;

        for (const item of itemsToPack) {
            if (item.h > PACKER_HEIGHT) {
                console.warn("Item taller than fixed roll height (rollWidth), skipping");
                continue;
            }
            if (item.w > PACKER_WIDTH) {
                 console.warn("Item wider than max length (rollLength), skipping");
                 continue;
            }

            // Packer fit:
            // We want to pack Left-to-Right (X) but fill Top-to-Bottom (Y) first.
            // Our GuillotinePacker sorts freeRects by X (Leftmost).
            
            let pos = packer.fit(item.w, item.h);
            
            if (!pos) {
                // Page full, start new page
                pages.push(currentPageItems);
                currentPageItems = [];
                currentPageIndex++;
                packer = new GuillotinePacker(PACKER_WIDTH, PACKER_HEIGHT);
                pos = packer.fit(item.w, item.h);
            }

            if (pos) {
                item.x = pos.x;
                item.y = pos.y;
                item.rotated = pos.rotated;
                item.pageIndex = currentPageIndex;
                
                // If rotated, we swap w and h for rendering logic
                if (pos.rotated) {
                    const temp = item.w;
                    item.w = item.h;
                    item.h = temp;
                }
                
                currentPageItems.push(item);
            } else {
                console.error("Item could not fit even in new page!", item);
            }
        }
        
        if (currentPageItems.length > 0) {
            pages.push(currentPageItems);
        }

        // 3. Create Output PDF
        const outputPdf = await PDFDocument.create();
        
        outputPdf.setTitle('DTF Print Job');
        outputPdf.setSubject('Nesting Output');
        outputPdf.setProducer('MainTextildruck Manager');
        outputPdf.setCreator('MainTextildruck Manager');

        for (let pIdx = 0; pIdx < pages.length; pIdx++) {
            const pageItems = pages[pIdx];
            if (!pageItems || pageItems.length === 0) continue;
            
            // Determine Page Dimensions
            // Height = Fixed (User RollWidth)
            // Width = Used Width (Max X + W)
            
            const maxX = pageItems.reduce((max, item) => Math.max(max, (item.x || 0) + item.w), 0);
            const pageWidth = maxX; 
            const pageHeight = pdfHeightFixedPoints;

            const page = outputPdf.addPage([pageWidth, pageHeight]);
            
            for (const item of pageItems) {
                if (item.sourceIndex === undefined || item.x === undefined || item.y === undefined) continue;
                
                const source = sourceDocs[item.sourceIndex];
                
                // Embed page
                const [embeddedPage] = await outputPdf.embedPages(source.pdf.getPages().slice(0, 1));
                
                // Position:
                // PDF Origin is Bottom-Left.
                // Packer Origin is Top-Left (0,0).
                
                // x = item.x
                // y = pageHeight - item.y - item.h
                
                const drawX = item.x + (paddingPoints / 2);
                const drawY = pageHeight - item.y - item.h + (paddingPoints / 2);
                
                if (item.rotated) {
                    // Manually apply rotation using PDF operators because drawPage rotation option is unreliable in this version
                    // Save Graphics State
                    page.pushOperators(PDFOperator.of('q' as any));
                    
                    // Translate to Anchor Point (Top-Left of the box)
                    // The box is at [drawX, drawY] with dimensions [source.height, source.width]
                    // We want to anchor at the top-left of this box: (drawX, drawY + source.width)
                    // PDFOperator.of expects args as array of specific types, we can use 'as any' to bypass for numbers
                    page.pushOperators(PDFOperator.of('cm' as any, [1, 0, 0, 1, drawX, drawY + source.width] as any));
                    
                    // Rotate -90 degrees (270 degrees)
                    // -90 deg rotation matrix: [0, -1, 1, 0, 0, 0]
                    page.pushOperators(PDFOperator.of('cm' as any, [0, -1, 1, 0, 0, 0] as any));
                    
                    // Draw page at (0,0) relative to the transformed coordinate system
                    page.drawPage(embeddedPage, {
                        x: 0,
                        y: 0,
                        width: source.width,
                        height: source.height
                    });
                    
                    // Restore Graphics State
                    page.pushOperators(PDFOperator.of('Q' as any));
                } else {
                    page.drawPage(embeddedPage, {
                        x: drawX,
                        y: drawY,
                        width: source.width,
                        height: source.height
                    });
                }
            }
        }

        const pdfBytes = await outputPdf.save();
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const outputFilename = `DTF_Job_${timestamp}.pdf`;
        const outputPath = path.join(UPLOAD_DIR, outputFilename);

        await fs.writeFile(outputPath, pdfBytes);

        // Generate Thumbnail for the output PDF
        try {
            // pdftoppm with -singlefile appends .png to the output root name
            const thumbRoot = path.join(UPLOAD_DIR, `${outputFilename}_thumb`);
            
            await execFileAsync('pdftoppm', [
                '-png',
                '-singlefile',
                '-scale-to', '300',
                outputPath,
                thumbRoot
            ]);
        } catch (e) {
            console.error('Failed to generate thumbnail for output PDF:', e);
        }

        res.json({
            success: true,
            url: `/uploads/${outputFilename}`,
            pages: pages.length
        });

    } catch (error) {
        console.error('DTF Generation Error:', error);
        res.status(500).json({ success: false, error: 'Internal Server Error' });
    }
});

export default router;